version: '1'

services:
  
  mongoMonolith:
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - dbdata:/data/db
  
  mongoServers:
    image: mongo
    ports:
      - '27019:27017'
    volumes:
      - dbservers:/data/db
  
  mongoChannels:
    image: mongo
    ports:
      - '27020:27017'
    volumes:
      - dbchannels:/data/db
  
  mongoMessages:
    image: mongo
    ports:
      - '27021:27017'
    volumes:
      - dbmessages:/data/db
  
  netReact-Monolith:
    image: netreact-monolith
    build:
      context: .
      dockerfile: ./NetReactMonolith/Dockerfile
    ports:
      - '7153:8080'
    depends_on:
      - mongoMonolith
        
  netReact-Auth:
    image: netreact-authservice
    build: 
      context: .
      dockerfile: ./NetReact.AuthService/Dockerfile
    ports:
      - '7154:8080'
    
  netReact-ServerManagement:
    image: netreact-servermanagementservice
    build:
      context: .
      dockerfile: ./NetReact.ServerManagementService/Dockerfile
    ports:
      - '7155:8080'
    depends_on:
      - mongoServers
  
  netReact-ChannelManagement:
    image: netreact-channelmanagementservice
    build:
      context: .
      dockerfile: ./NetReact.ChannelManagementService/Dockerfile
    ports:
      - '7156:8080'
    environment:
      - ServiceUrls__ServersService=http://netReact-ServerManagement:8080
    depends_on:
      - mongoChannels
  
  netReact-Messaging:
    image: netreact-messagingservice
    build:
      context: .
      dockerfile: ./NetReact.MessagingService/Dockerfile
    ports:
      - '7157:8080'
    environment:
      - ServiceUrls__ChannelsService=http://netReact-ChannelManagement:8080
      - ASPNETCORE_DBIMAGES=DBIMAGES
    depends_on:
      - mongoMessages

volumes:
  dbdata:
  dbservers:
  dbchannels:
  dbmessages: