version: '1'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network
  
  apiServer:
    build:
      context: .
      dockerfile: ./RESTfulAPI/Dockerfile
    image: netreactback
    ports:
      - '7153:8080'
    environment:
      - ASPNETCORE_DBIMAGES=DBIMAGES

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge