version: '1'

services:
          
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    
  mongo-express:
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
  
  apiServer:
    image: netreactback
    build:
      context: .
      dockerfile: ./NetReactMonolith/Dockerfile
    ports:
      - '7153:8080'
    environment:
      - ASPNETCORE_DBIMAGES=DBIMAGES
    depends_on:
      - mongo

volumes:
  dbdata: