version: '1'

services:
          
  mongo:
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - dbdata:/data/db
  
  netReact-Monolith:
    image: netreact-monolith
    build:
      context: .
      dockerfile: ./NetReactMonolith/Dockerfile
    ports:
      - '7153:8080'
    environment:
      - ASPNETCORE_DBIMAGES=DBIMAGES
    depends_on:
      - mongo
        
  netReact-Auth:
    image: netreact-authservice
    build: 
      context: .
      dockerfile: ./NetReact.AuthService/Dockerfile
    ports:
      - '7154:8080'

volumes:
  dbdata: