apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-servermanagement
  namespace: netreact-servermanagement
spec:
  selector:
    matchLabels:
      app: db-servermanagement
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db-servermanagement
    spec:
      containers:
        - name: db-servermanagement
          image: mongo
          ports:
            - containerPort: 27017
              name: db-sm
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: db-servermanagement-claim

---

apiVersion: v1
kind: Service
metadata:
  name: db-servermanagement
  namespace: netreact-servermanagement
spec:
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30002
      protocol: TCP
  selector:
    app: db-servermanagement
  type: NodePort