apiVersion: apps/v1
kind: Deployment
metadata:
  name: netreact-messagingworker
  namespace: netreact-messaging
spec:
  selector:
    matchLabels:
      app: netreact-messagingworker
  replicas: 2
  template:
    metadata:
      labels:
        app: netreact-messagingworker
    spec:
      containers:
        - name: netreact-messagingworker
          image: netreact-messagingworker:1.0
          ports:
            - containerPort: 8080
          env:
            - name: Connections__Database
              value: "mongodb://db-messaging:27017/"

---

apiVersion: v1
kind: Service
metadata:
  name: netreact-messagingworker
  namespace: netreact-messaging
spec:
  type: LoadBalancer
  selector:
    app: netreact-messagingworker
  ports:
    - port: 7157
      targetPort: 8080