apiVersion: apps/v1
kind: Deployment
metadata:
  name: netreact-messagingworker
  namespace: netreact-messaging
spec:
  selector:
    matchLabels:
      app: netreact-messagingworker
  replicas: 1
  template:
    metadata:
      labels:
        app: netreact-messagingworker
    spec:
      containers:
        - name: netreact-messagingworker
          image: netreact-messagingworker:1.0
          env:
            - name: Connections__Database
              value: "mongodb://db-messaging:27017/"