apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-messaging
  namespace: netreact-messaging
spec:
  selector:
    matchLabels:
      app: db-messaging
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db-messaging
    spec:
      containers:
        - name: db-messaging
          image: mongo
          ports:
            - containerPort: 27017
              name: db-ms
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: db-messaging-claim

---

apiVersion: v1
kind: Service
metadata:
  name: db-messaging
  namespace: netreact-messaging
spec:
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30004
      protocol: TCP
  selector:
    app: db-messaging
  type: NodePort