apiVersion: apps/v1
kind: Deployment
metadata:
  name: netreact-signaling
  namespace: netreact-signaling
spec:
  selector:
    matchLabels:
      app: netreact-signaling
  replicas: 1
  template:
    metadata:
      labels:
        app: netreact-signaling
    spec:
      containers:
        - name: netreact-signaling
          image: netreact-signaling:1.0
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: netreact-signaling
  namespace: netreact-signaling
spec:
  type: LoadBalancer
  selector:
    app: netreact-signaling
  ports:
    - port: 7153
      targetPort: 8080